# Generated by Django 4.1.4 on 2022-12-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
