# Generated by Django 4.1.4 on 2022-12-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_countdown_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
